# Generated by Django 4.2.7 on 2025-05-18 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("hi", "Hindi"),
                ],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="supabase_uid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="light",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_distance",
            field=models.PositiveIntegerField(
                default=0, help_text="Total distance traveled in kilometers"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_trips",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TravelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_destinations", models.JSONField(blank=True, default=list)),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "accommodation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "travel_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("luxury", "Luxury"),
                            ("budget", "Budget"),
                            ("adventure", "Adventure"),
                            ("cultural", "Cultural"),
                            ("relaxation", "Relaxation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("interests", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
