services:
  - type: web
    name: wanderai-backend
    runtime: python
    buildCommand: pip install -r requirements/production.txt
    startCommand: cd wanderlustai_backend && gunicorn wanderlustai_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: wanderlustai_backend.settings
      - key: DATABASE_URL
        fromDatabase:
          name: wanderai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "wanderai-backend.onrender.com,render.com,localhost,127.0.0.1"
      - key: DJANGO_DEBUG
        value: "False"

databases:
  - name: wanderai-db
    databaseName: wanderai
    user: wanderai_user
    plan: free 