# Generated by Django 4.2.7 on 2025-05-17 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transportationdetail",
            name="journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transportation",
                to="travels.journey",
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
