# Generated by Django 4.2.7 on 2025-05-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheckLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "database_status",
                    models.CharField(default="unchecked", max_length=20),
                ),
                ("openai_status", models.CharField(default="unchecked", max_length=20)),
                (
                    "ola_maps_status",
                    models.CharField(default="unchecked", max_length=20),
                ),
                ("error_details", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="ai_services_timesta_2e4120_idx"
                    ),
                    models.Index(
                        fields=["status"], name="ai_services_status_e424ec_idx"
                    ),
                ],
            },
        ),
    ]
